---
- name: Configure and Install Vector
  block:
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_release }}/vector_{{ vector_version }}_amd64.deb"
        dest: "./vector_{{ vector_version }}_amd64.deb"
        mode: "0755"
    - name: Install Vector packages
      become: true
      ansible.builtin.apt:
        deb: vector_{{ vector_version }}_amd64.deb
      notify: Start Vector service
    - name: Copy config
      become: true
      ansible.builtin.template:
        src: "{{ vector_template }}"
        dest: "{{ vector_config_file }}"
        mode: "0644"
      notify: Start Vector service
